wappa/urls.py
#!/usr/bin/env python
# -*- coding:utf-8 -*-

from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf.urls.i18n import i18n_patterns
from apps.photo.views import home, home_files

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = patterns('',
    url(r'^(?P<filename>(robots.txt)|(humans.txt))$',
        home_files, name='home-files'),
)

urlpatterns += i18n_patterns(
    '',
    url(r'^admin/', include(admin.site.urls)),
    url(r'^dashboard/', include('apps.photo.dashboard_urls', namespace='dashboard')),
    url(r'^$', home, name='home'),
)

if settings.DEBUG == True:
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/photo/models.py
#!/usr/bin/env python
# -*- coding:utf-8 -*-

from django.db import models
from datetime import datetime
from hvad.models import TranslatableModel, TranslatedFields
from taggit.managers import TaggableManager
from django.contrib.auth.models import User
from django.utils.translation import ugettext_lazy as _
from apps.taxonomy.models import Country, Domain, Status, Gender

from django.core import urlresolvers
from django.contrib.contenttypes.models import ContentType

import os
from django.conf import settings

class Photo(models.Model):
    # function called after the save function is called to rename image filename
    def content_file_name(instance, filename):
        fname, fext = os.path.splitext(filename)
        filename = "%s_%s_%s%s%s%s" % (instance.author_id,
                                        instance.id,
                                        instance.width, "x", instance.height,
                                        fext)
        full_filename = os.path.join('wappa', filename)
        # remove file if exists
        if os.path.isfile(os.path.join(settings.MEDIA_ROOT, full_filename)):
            os.remove(os.path.join(settings.MEDIA_ROOT, full_filename))
        return full_filename

    title = models.CharField(max_length=200, verbose_name=_('title'))
    description = models.TextField(max_length=200, verbose_name=_('description'))

    author = models.ForeignKey(User, verbose_name=_('author'))
    license = models.CharField(max_length=200, verbose_name=_('license'))
    width = models.IntegerField(verbose_name=_('width'))
    height = models.IntegerField(verbose_name=_('heigth'))
    camera_model = models.CharField(max_length=200, verbose_name=_('camera_model'))
    sensibilite_iso = models.CharField(max_length=200, verbose_name=_('sensibilite_iso'))
    focal = models.CharField(max_length=200, verbose_name=_('focal'))
    ouverture = models.CharField(max_length=200, verbose_name=_('ouverture'))
    temps_de_pause = models.CharField(max_length=200, verbose_name=_('temps_de_pause'))
    countries = models.ManyToManyField(Country, verbose_name=_('countries'))
    image = models.ImageField(max_length=200, upload_to=content_file_name)
    exif_date = models.DateField(verbose_name=_('date exif'), default=datetime.now)
    pub_date = models.DateField(verbose_name=_('date published'), default=datetime.now)
    status = models.ForeignKey(Status, verbose_name=_('status'))

    photo_tags = TaggableManager(blank=True)

    def __str__(self):
        return "%s" % self.title

    def get_change_urls(self):
        content_type = ContentType.objects.get_for_model(self.__class__)
        return urlresolvers.reverse("admin:%s_%s_change" % (content_type.app_label,
                                                            content_type.model),
                                                            args=(self.id,))

    @property
    def filename(self):
        return os.path.basename(self.image.name)

    def save(self, *args, **kwargs):
        # save image, to set the id object
        if self.id is None:
            tmp_img, self.image = self.image, None
            #super(Photo, self).save(*args, **kwargs)
            super().save(*args, **kwargs)
            self.image = tmp_img

        # self.image has changed, so save is called again
        super().save(*args, **kwargs)


class Pack(TranslatableModel):
    translations = TranslatedFields(
        title = models.CharField(max_length=200, verbose_name=_('title')),
        description = models.TextField(max_length=200, verbose_name=_('description'))
        )
    pack_type = models.ForeignKey(Gender, verbose_name=_('type'))
    status = models.ForeignKey(Status, verbose_name=_('status'))
    countries = models.ManyToManyField(Country)
    domain = models.ForeignKey(Domain, verbose_name=_('domain'))
    image = models.ForeignKey(Photo, null=True, blank=True, verbose_name=_('image preview'))

    pub_date = models.DateField(default=datetime.now, verbose_name=_('date published'))
    begin_date = models.DateField(default=datetime.now, verbose_name=_("begin_date"))
    end_date = models.DateField(default=datetime.now, verbose_name=_("end_date"))

    photos = models.ManyToManyField(Photo, blank=True, related_name='packs')

    pack_tags = TaggableManager(blank=True)

    def __str__(self):
        return "%s" % self.lazy_translation_getter('title', str(self.pk))

    def get_change_urls(self):
        ct = ContentType.objects.get_for_model(self.__class__)
        return urlresolvers.reverse("admin:%s_%s_change" % (ct.app_label, ct.model), args=(self.id,))

apps/photo/forms.py
#!/usr/bin/env python
# -*- coding:utf-8 -*-

from django.forms import ModelForm
from django import forms
from django.contrib.auth.models import User
from apps.photo.models import Pack, Photo, PackTranslation
from django.utils.translation import ugettext_lazy as _


class PhotoForm(ModelForm):
    class Meta:
        model = Photo
        fields = ("author", "license", "width", "height",
                  "camera_model", "sensibilite_iso", "focal",
                  "ouverture", "temps_de_pause", "countries",
                  "image", "exif_date", "pub_date", "status", "photo_tags",
                  "title", "description")


class BasePackForm(ModelForm):

    class Meta:
        model = Pack
        fields = ("pack_type", "status",
                  "pub_date", "begin_date", "end_date", "photos",
                  "pack_tags", "countries", "domain", "image")
        widgets = {
             'image': forms.TextInput(),
             'photos': forms.TextInput(),
             }

class PackForm(BasePackForm):
    title_fr = forms.CharField(label=_("French Title"),
                               widget=forms.TextInput,
                               required=True,
                               help_text=_('French Title'),)
    description_fr = forms.CharField(label=_("French Description"),
                                     widget=forms.Textarea,
                                     required=True,
                                     help_text=_('French Description'))
    title_en = forms.CharField(label=_("English Title"),
                               widget=forms.TextInput,
                               required=True,
                               help_text=_('English Title'))
    description_en = forms.CharField(label=_("English Description"),
                                     widget=forms.Textarea,
                                     required=True,
                                     help_text=_('English Description'))

    class Meta(BasePackForm.Meta):
        fields = BasePackForm.Meta.fields + ('title_fr', 'description_fr', 'title_en', 'description_en')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        #self.fields['photos'].choices = [(x[0],str(x[0])) for x in Photo.objects.values_list('id')]
        # self.fields['image'].choices = [(x[0],str(x[0])) for x in Photo.objects.values_list('id')]

        if 'instance' in kwargs:
            pck = kwargs.pop('instance')
            if pck.id:
                #self.fields['photos'].queryset = pck.photos.values_list('id')
                try:
                    self.fields['title_fr'].initial = pck.translations.get_language('fr').title
                    self.fields['title_en'].initial = pck.translations.get_language('en').title
                    self.fields['description_fr'].initial = pck.translations.get_language('fr').description
                    self.fields['description_en'].initial = pck.translations.get_language('en').description
                except:
                    pass

    def clean(self):
        self.cleaned_data = super().clean()

apps/photo/views.py
#!/usr/bin/env python
# -*- coding:utf-8 -*-

from django.shortcuts import render
from django.http import HttpResponse

# Create your views here.

def home_files(request, filename):
    return render(request,
                  filename,
                  {},
                  content_type="text/plain")

def home(request):
    return HttpResponse("hello world")

apps/photo/templates/photo/base.html
{% load admin_static %}{% load firstof from future %}<!DOCTYPE html>
<html lang="{{ LANGUAGE_CODE|default:"en-us" }}" {% if LANGUAGE_BIDI %}dir="rtl"{% endif %}>
<head>
<title>{% block title %}{% endblock %}</title>
<link rel="stylesheet" type="text/css" href="{% block stylesheet %}{% static "admin/css/base.css" %}{% endblock %}" />
{% block extrastyle %}{% endblock %}
<!--[if lte IE 7]><link rel="stylesheet" type="text/css" href="{% block stylesheet_ie %}{% static "admin/css/ie.css" %}{% endblock %}" /><![endif]-->
{% if LANGUAGE_BIDI %}<link rel="stylesheet" type="text/css" href="{% block stylesheet_rtl %}{% static "admin/css/rtl.css" %}{% endblock %}" />{% endif %}
<script type="text/javascript">window.__admin_media_prefix__ = "{% filter escapejs %}{% static "admin/" %}{% endfilter %}";</script>
<script type="text/javascript">window.__admin_utc_offset__ = "{% filter escapejs %}{% now "Z" %}{% endfilter %}";</script>
{% block extrahead %}{% endblock %}
{% block blockbots %}<meta name="robots" content="NONE,NOARCHIVE" />{% endblock %}
</head>
{% load i18n %}

<body class="{% if is_popup %}popup {% endif %}{% block bodyclass %}{% endblock %}">

<!-- Container -->
<div id="container">

    {% if not is_popup %}
    <!-- Header -->
    <div id="header">
        <div id="branding">
        {% block branding %}{% endblock %}
        </div>
        {% if user.is_active and user.is_staff %}
        <div id="user-tools">
            {% block welcome-msg %}
                {% trans 'Welcome,' %}
                <strong>{% firstof user.get_short_name user.get_username %}</strong>.
            {% endblock %}
            {% block userlinks %}
                {% url 'django-admindocs-docroot' as docsroot %}
                {% if docsroot %}
                    <a href="{{ docsroot }}">{% trans 'Documentation' %}</a> /
                {% endif %}
                {% if user.has_usable_password %}
                <a href="{% url 'dashboard:password_change' %}">{% trans 'Change password' %}</a> /
                {% endif %}
                <a href="{% url 'dashboard:logout' %}">{% trans 'Log out' %}</a>
            {% endblock %}
        </div>
        {% endif %}
        {% block nav-global %}{% endblock %}
    </div>
    <!-- END Header -->
    {% block breadcrumbs %}
    <div class="breadcrumbs">
    <a href="{% url 'dashboard:index' %}">{% trans 'Home' %}</a>
    {% if title %} &rsaquo; {{ title }}{% endif %}
    </div>
    {% endblock %}
    {% endif %}

    {% block messages %}
        {% if messages %}
        <ul class="messagelist">{% for message in messages %}
          <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message|capfirst }}</li>
        {% endfor %}</ul>
        {% endif %}
    {% endblock messages %}

    <!-- Content -->
    <div id="content" class="{% block coltype %}colM{% endblock %}">
        {% block pretitle %}{% endblock %}
        {% block content_title %}{% if title %}<h1>{{ title }}</h1>{% endif %}{% endblock %}
        {% block content %}
        {% block object-tools %}{% endblock %}
        {{ content }}
        {% endblock %}
        {% block sidebar %}{% endblock %}
        <br class="clear" />
    </div>
    <!-- END Content -->

    {% block footer %}<div id="footer"></div>{% endblock %}
</div>
<!-- END Container -->

</body>
</html>

apps/photo/templates/photo/base_site.html
{% extends "photo/base.html" %}
{% load i18n admin_static %}

{% block title %}{{ title }} | {{ site_title|default:_('Django site admin') }}{% endblock %}

{% block branding %}
<h1 id="site-name"><a href="{% url 'dashboard:index' %}">{{ site_header|default:_('Django administration') }}</a></h1>
{% endblock %}

{% block nav-global %}{% endblock %}

apps/photo/templates/photo/dashboard.html
{% extends "photo/base_site.html" %}
{% load i18n admin_static %}

{% block extrastyle %}{{ block.super }}<link rel="stylesheet" type="text/css" href="{% static "admin/css/dashboard.css" %}" />{% endblock %}

{% block coltype %}colMS{% endblock %}

{% block bodyclass %}{{ block.super }} dashboard{% endblock %}

{% block breadcrumbs %}{% endblock %}

{% block content %}
<div id="content-main">
custom dashboard

<ul>
<li><a href="{% url 'dashboard:packs' %}">{% trans 'Packs' %}</a></li>
<li><a href="{% url 'dashboard:photos' %}">{% trans 'Photos' %}</a></li>
<li><a href="{% url 'dashboard:add_pack' %}">{% trans 'Add pack' %}</a></li>
<li><a href="{% url 'dashboard:add_photo' %}">{% trans 'Add photo' %}</a></li>
</ul>

</div>
{% endblock %}

{% block sidebar %}
{% endblock %}